<?php
namespace Outspaced\GoogleChartMakerBundle\Tests\Element;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-05 at 12:38:42.
 */
class CustomAxisLabelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Outspaced\GoogleChartMakerBundle\Chart\Element\CustomAxisLabel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Outspaced\GoogleChartMakerBundle\Chart\Element\CustomAxisLabel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Outspaced\GoogleChartMakerBundle\Chart\Element\CustomAxisLabel::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\GoogleChartMakerBundle\Chart\Element\CustomAxisLabel::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\GoogleChartMakerBundle\Chart\Element\CustomAxisLabel::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
