language: php
php:
  - 5.5
  - 5.4
script: phpunit --coverage-clover=coverage.clover
after-script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
