<?php
namespace Outspaced\ChartsiaBundle\Tests\Axis;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-08 at 22:11:12.
 */
class AxisTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Outspaced\ChartsiaBundle\Chart\Axis\Axis
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \Outspaced\ChartsiaBundle\Chart\Axis\Axis;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::setLabel
     * @todo   Implement testSetLabel().
     */
    public function testSetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::getLabel
     * @todo   Implement testGetLabel().
     */
    public function testGetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::setRange
     * @todo   Implement testSetRange().
     */
    public function testSetRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::getRange
     * @todo   Implement testGetRange().
     */
    public function testGetRange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::setTick
     * @todo   Implement testSetTick().
     */
    public function testSetTick()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Axis::getTick
     * @todo   Implement testGetTick().
     */
    public function testGetTick()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
