<?php
namespace Outspaced\ChartsiaBundle\Tests\Axis;

use Outspaced\ChartsiaBundle\Chart\Axis;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-08 at 22:12:17.
 */
class LabelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Axis\Label
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Axis\Label;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Label::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Axis\Label::getKey
     * @todo   Implement testGetKey().
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
