<?php

namespace Outspaced\ChartsiaBundle\Tests\Config;

use \Outspaced\ChartsiaBundle\Chart\Config\Title;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-03 at 21:46:30.
 */
class TitleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Title
     */
    protected $object;

    /**
     */
    protected function setUp()
    {
        $this->object = new Title;
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Config\Title::setTitle
     */
    public function testSetTitle()
    {
        $this->object->setTitle('Hello. Is it me you\'re looking for?');
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Config\Title::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
        $this->object->setTitle('Hello. Is it me you\'re looking for?');
        $this->assertEquals('Hello. Is it me you\'re looking for?', $this->object->getTitle());
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Config\Title::setColor
     * @todo   Implement testSetColor().
     */
    public function testSetColor()
    {
        $color = new \Outspaced\ChartsiaBundle\Chart\Component\Color();
        $this->object->setColor($color);
    }

    /**
     * @covers Outspaced\ChartsiaBundle\Chart\Config\Title::getColor
     * @todo   Implement testGetColor().
     */
    public function testGetColor()
    {
        $color = new \Outspaced\ChartsiaBundle\Chart\Component\Color();
        $this->object->setColor($color);

        $this->assertInstanceOf('\Outspaced\ChartsiaBundle\Chart\Component\Color', $this->object->getColor());
    }
}
